"""Authentication backend for the demo server."""

import random

from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from reviewboard.accounts.backends.base import BaseAuthBackend
from reviewboard.reviews.models import Group

from rbdemo.forms import DemoAuthSettingsForm


class DemoAuthBackend(BaseAuthBackend):
    """Authentication backend for the demo server.

    This allows people to log in with a pre-generated username and password,
    which will be shown on the login page.

    The page will try to show a username that has not already been created.
    This is generated by taking a prefix (defaults to "guest") and appending
    a random number in a range, and showing that as the username.

    The goal is to give people a clean session. Depending on the random
    numbers generated and the traffic on the server, this may not be
    feasible without too many queries, so we'll fall back on the last
    attempt.

    After creating a user for the first time, that user will be added to
    the configured review groups, in order to give them something they can
    see in their dashboard.
    """

    backend_id = 'demo'
    name = _('Demo Server')
    settings_form = DemoAuthSettingsForm

    MAX_USER_CHECKS = 10

    @property
    def login_instructions(self):
        """The instructions to show on the login screen.

        Type:
            str
        """
        settings = self.extension.settings
        user_prefix = settings.get('auth_user_prefix')
        max_guest_id = settings.get('auth_user_max_id')
        demo_password = settings.get('auth_password')

        # Try to find a username that hasn't been taken yet. We'll only
        # try up to a certain number of times, though.
        for i in range(self.MAX_USER_CHECKS):
            username = '%s%d' % (user_prefix, random.randint(1, max_guest_id))

            if not User.objects.filter(username=username).exists():
                break
        else:
            # Give up and just use the basic "guest" name. They might see other
            # users' data but that's better than getting an error.
            username = user_prefix

        return (_('To log into the demo server, use username "%s", '
                  'password "%s"')
                % (username, demo_password))

    def __init__(self, *args, **kwargs):
        """Initialize the authentication backend.

        Args:
            *args (tuple):
                Positional arguments to pass to the base class.

            **kwargs (dict):
                Keyword arguments to pass to the base class.
        """
        from rbdemo.extension import DemoExtension

        super(DemoAuthBackend, self).__init__(*args, **kwargs)
        self.extension = DemoExtension.instance

    def authenticate(self, request, username, password):
        """Authenticate a user.

        Args:
            request (django.http.HttpRequest):
                The request object.

            username (str):
                The username to authenticate.

            password (str):
                The password to authenticate.

        Returns:
            django.contrib.auth.models.User:
            The authenticated user. ``None`` if the user could not be
            authenticated.
        """
        settings = self.extension.settings
        user_prefix = settings.get('auth_user_prefix')
        demo_password = settings.get('auth_password')

        username = username.strip()

        if password == demo_password and username.startswith(user_prefix):
            # We know this is a guest user, and the password is valid.
            # We're going to take the ID from the end of the username,
            # make sure it's an integer in the expected range, and then
            # validate.
            guest_id = username[len(user_prefix):]

            try:
                # Check that the ID is in the allowed range.
                if 0 < int(guest_id) <= settings.get('auth_user_max_id'):
                    return self.get_or_create_user(username, None, password)
            except ValueError:
                pass

        return None

    def get_or_create_user(self, username, request, password=None):
        """Return a user object.

        Args:
            username (str):
                The username of the user.

            request (django.http.HttpRequest):
                The request object.

            password (str, unused):
                The user's password.

        Returns:
            django.contrib.auth.models.User:
            The user object.
        """
        user, is_new = User.objects.get_or_create(username=username)

        if is_new:
            user.set_unusable_password()
            user.save()

            group_names = self.extension.settings.get('auth_default_groups')

            # Add the user to the default groups, so that they can see some
            # review requests on their dashboard.
            for group_name in group_names:
                groups = Group.objects.get(name=group_name)
                groups.users.add(user)

        return user
